version: '3.8'

name: antarctica-explorer

services:
  db:
     image: postgres:latest
     environment:
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}
       POSTGRES_DB_ENCODING: UTF8
     ports:
       - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
     command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
     volumes:
       - ./postgresql/data:/var/lib/postgresql/data
       - ./postgresql:/postgresql
       - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: antarctica-explorer-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_HOST_PORT}:${API_CONTAINER_PORT}
    env_file: .env
    environment:
      - spring.datasource.url=${DB_URL}
      - spring.datasource.username=${DB_USER}
      - spring.datasource.password=${DB_PASSWORD}
    depends_on:
      - db