TABLE antarctic.cruise_lines {
  cruise_line_id SERIAL
  name VARCHAR(50) [NOT NULL]
  website VARCHAR(255) [NOT NULL]
  fleet_website VARCHAR(255) [NOT NULL]
  expedition_website VARCHAR(255) [NOT NULL]
  logo TEXT [NOT NULL]
  PRIMARY KEY (cruise_line_id)
}

TABLE antarctic.expeditions {
  cruise_line_id INTEGER [NOT NULL]
  expedition_id SERIAL
  website TEXT
  name VARCHAR(255) [NOT NULL]
  description TEXT[]
  highlights TEXT[]
  departing_from VARCHAR(100)
  arriving_at VARCHAR(100)
  duration VARCHAR(50) [NOT NULL]
  starting_price DECIMAL(10, 4)
  photo_url TEXT
  PRIMARY KEY (expedition_id)
}
ref: antarctic.expeditions.cruise_line_id > antarctic.cruise_lines.cruise_line_id

TABLE antarctic.gallery {
  photo_id SERIAL
  expedition_id INTEGER [NOT NULL]
  photo_url TEXT [NOT NULL]
  alt TEXT
  PRIMARY KEY (photo_id)
}
ref: antarctic.gallery.expedition_id > antarctic.expeditions.expedition_id

TABLE antarctic.vessels {
  cruise_line_id INTEGER [NOT NULL]
  vessel_id SERIAL
  name VARCHAR [NOT NULL]
  capacity INTEGER [NOT NULL]
  cabins INTEGER
  description TEXT[]
  website TEXT
  photo_url TEXT [NOT NULL]
  PRIMARY KEY (cruise_id)
}
ref: antarctic.vessels.cruise_line_id > antarctic.cruise_lines.cruise_line_id

TABLE antarctic.itineraries {
  itinerary_id SERIAL
  expedition_id INTEGER [NOT NULL]
  name VARCHAR(255)
  departing_from VARCHAR(100)
  arriving_at VARCHAR(100)
  duration VARCHAR(10) [NOT NULL]
  map_url TEXT
  PRIMARY KEY (itinerary_id)
}
ref: antarctic.itineraries.expedition_id > antarctic.expeditions.expedition_id

TABLE antarctic.itinerary_details {
  detail_id SERIAL
  itinerary_id INTEGER [NOT NULL]
  day VARCHAR(10) [NOT NULL]
  header VARCHAR(255) [NOT NULL]
  content TEXT[] [NOT NULL]
  PRIMARY KEY (detail_id)
}
ref: antarctic.itinerary_details.itinerary_id > antarctic.itineraries.itinerary_id

TABLE antarctic.departures {
  departure_id SERIAL
  expedition_id INTEGER [NOT NULL]
  vessel_id INTEGER [NOT NULL]
  itinerary_id INTEGER [NOT NULL]
  name VARCHAR
  start_date DATE [NOT NULL]
  end_date DATE [NOT NULL]
  starting_price DECIMAL(10, 4)
  discounted_price DECIMAL(10, 4)
  website TEXT
  PRIMARY KEY (departure_id)
}
ref: antarctic.departures.expedition_id > antarctic.expeditions.expedition_id
ref: antarctic.departures.vessel_id > antarctic.vessels.vessel_id
ref: antarctic.departures.itinerary_id > antarctic.itineraries.itinerary_id

TABLE antarctic.extensions {
  extension_id SERIAL
  cruise_line_id INTEGER [NOT NULL]
  name VARCHAR [NOT NULL]
  starting_price DECIMAL(10, 4)
  duration INTEGER
  photo_url TEXT [NOT NULL]
  website TEXT
  PRIMARY KEY (extension_id)
}
ref: antarctic.extensions.cruise_line_id > antarctic.cruise_lines.cruise_line_id

TABLE antarctic.expeditions_extensions {
  extension_id INTEGER [NOT NULL]
  expedition_id INTEGER [NOT NULL]
}
ref: antarctic.expeditions_extensions.expedition_id > antarctic.expeditions.expedition_id
ref: antarctic.expeditions_extensions.extension_id > antarctic.extensions.extension_id